language: julia
os:
    - linux
julia:
    - 1.0  # JuMP currently supports Julia 1.0 LTS
notifications:
    email: false
sudo: false
branches:
  only:
    - master

jobs:
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip